version: "3.4"

services:

  #command-service:
  #  container_name: command-service
  #  build:
  #    context: ./command
  #    dockerfile: Dockerfile

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  eventstore.db:
    image: eventstore/eventstore:23.10.0-bookworm-slim
    container_name: eventstore.db
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
